<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<PlatformTarget>x64</PlatformTarget>
		<Platforms>AnyCPU;x64</Platforms>
		<AssemblyName>AddinVeMong</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<Resource Include="Resources\Images\*.png" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="RevitAPI">
			<HintPath>C:\Program Files\Autodesk\Revit 2025\RevitAPI.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="RevitAPIUI">
			<HintPath>C:\Program Files\Autodesk\Revit 2025\RevitAPIUI.dll</HintPath>
			<Private>False</Private>
		</Reference>
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Resources\Localization\Resource.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Resource.resx</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Update="Resources\Localization\Resource.en.resx">
	    <Generator></Generator>
	    <CustomToolNamespace></CustomToolNamespace>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Resources\Localization\Resource.resx">
	    <Generator>PublicResXFileCodeGenerator</Generator>
	    <LastGenOutput>Resource.Designer.cs</LastGenOutput>
	    <CustomToolNamespace>AddinVeMong.Resources.Localization</CustomToolNamespace>
	  </EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
	  <Resource Update="Resources\Images\About.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Update="Resources\Images\Centric.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Update="Resources\Images\Eccentric.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Update="Resources\Images\EccentricChamfer.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Update="Resources\Images\CentricChamfer.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Update="Resources\Images\Help.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Update="Resources\Images\LoadFoundation.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Update="Resources\Images\LoadRebar.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Update="Resources\Images\Rebar.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Update="Resources\Images\Setting.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	</ItemGroup>

</Project>