//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddinVeMong.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AddinVeMong.Resources.Localization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo Thép.
        /// </summary>
        public static string BtnCreate {
            get {
                return ResourceManager.GetString("BtnCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu cài đặt.
        /// </summary>
        public static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích thước cột X (mm):.
        /// </summary>
        public static string ColWidthX {
            get {
                return ResourceManager.GetString("ColWidthX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích thước cột Y (mm):.
        /// </summary>
        public static string ColWidthY {
            get {
                return ResourceManager.GetString("ColWidthY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lớp bê tông bảo vệ (mm):.
        /// </summary>
        public static string ConcreteCover {
            get {
                return ResourceManager.GetString("ConcreteCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường kính (mm):.
        /// </summary>
        public static string Diameter {
            get {
                return ResourceManager.GetString("Diameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình chiếu đứng.
        /// </summary>
        public static string ElevationView {
            get {
                return ResourceManager.GetString("ElevationView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiều dài chân vịt (mm):.
        /// </summary>
        public static string FootHookLength {
            get {
                return ResourceManager.GetString("FootHookLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiều dài bẻ móc (mm):.
        /// </summary>
        public static string HookLength {
            get {
                return ResourceManager.GetString("HookLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ (Language):.
        /// </summary>
        public static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường kính thép dọc:.
        /// </summary>
        public static string MainDiameter {
            get {
                return ResourceManager.GetString("MainDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình chiếu bằng.
        /// </summary>
        public static string PlanView {
            get {
                return ResourceManager.GetString("PlanView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng thanh:.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. THÉP CỔ CỘT &amp; ĐAI.
        /// </summary>
        public static string SecColumn {
            get {
                return ResourceManager.GetString("SecColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. THÔNG SỐ CHUNG (MÓNG &amp; BÊ TÔNG).
        /// </summary>
        public static string SecGeneral {
            get {
                return ResourceManager.GetString("SecGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. THÉP CẠNH DÀI (PHƯƠNG X).
        /// </summary>
        public static string SecLongBar {
            get {
                return ResourceManager.GetString("SecLongBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. THÉP CẠNH NGẮN (PHƯƠNG Y).
        /// </summary>
        public static string SecShortBar {
            get {
                return ResourceManager.GetString("SecShortBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt hệ thống.
        /// </summary>
        public static string SettingTitle {
            get {
                return ResourceManager.GetString("SettingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khoảng cách a (mm):.
        /// </summary>
        public static string Spacing {
            get {
                return ResourceManager.GetString("Spacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiều dài chờ cột (mm):.
        /// </summary>
        public static string StarterLength {
            get {
                return ResourceManager.GetString("StarterLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường kính thép đai:.
        /// </summary>
        public static string StirrupDiameter {
            get {
                return ResourceManager.GetString("StirrupDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khoảng cách đai (mm):.
        /// </summary>
        public static string StirrupSpacing {
            get {
                return ResourceManager.GetString("StirrupSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao diện (Theme):.
        /// </summary>
        public static string ThemeLabel {
            get {
                return ResourceManager.GetString("ThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiết lập cốt thép móng đúng tâm.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
